// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztodisbbvecybqcvpknt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0b2Rpc2JidmVjeWJxY3Zwa250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjI2ODgsImV4cCI6MjA1OTMzODY4OH0.ATu02v2tAxCJQsyHtOyYMwGYb-iz9JimCI5MH67kkT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);